Check for VERSION file update on publishing new version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,5 +18,16 @@ jobs:
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
+      - name: Check that VERSION file is up-to-date
+        run: |
+          if [ ! -f VERSION ]; then
+            echo "VERSION file not found in repository"
+            exit 1
+          fi
+          if [ "v$(cat VERSION)" != "${{ env.VERSION_TAG }}" ]; then
+            echo "VERSION file does not match the release tag. Release tag: ${{ env.VERSION_TAG }}, VERSION file: $(cat VERSION)"
+            exit 1
+          fi
+
       - name: Build and push Docker image
         run: ./docker_build.sh -p -t "$VERSION_TAG"
